# -*- coding: utf-8 -*-
"""Assessment2B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11T0-vS2grZAAgVqoVtyeI2vSOYn7TJQF

###### Assessment

###### I am going to provide two .csv files , you are supposed to work on them and have to provide solutions to the following problems

###### import necessary libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""###### merge those two csv files (after getting as dataframes, get them as a single dataframe)"""

pd1=pd.read_csv("college_1.csv")
pd2=pd.read_csv("college_2.csv")
pd1.head()

pd2.head()

pd1.shape

pd2.shape

combined_list=[pd1,pd2]
data=pd.concat(combined_list,join="inner")
data

"""###### Take each csv file , split that csv file into multiple categories (example csv files are added in the repo)

###### consider if the codekata score exceeds 15000 points(present week) then make a csv on those observations as Exceeded expectations.csv
"""

EE=data[data["CodeKata Score"]>15000]
EE

EE.to_csv("Exceeded expectations.csv")

"""###### if  10000<codekata score<15000   (Reached_expectations.csv)


"""

RE=data[(data["CodeKata Score"]<=15000)&(data["CodeKata Score"]>10000)]
RE.to_csv("Reached_expectations.csv")

"""###### if  7000<codekata score<10000   (Needs_Improvement.csv)

"""

NI=data[(data["CodeKata Score"]<=10000)&(data["CodeKata Score"]>7000)]
NI.to_csv("Needs_Improvement.csv")

"""###### if  codekate score < 7000        (Unsatisfactory.csv)"""

US=data[data["CodeKata Score"]<=7000]
US.to_csv("Unsatisfactory.csv")

"""###### Average of previous week geekions vs this week geekions (i.e Previous Geekions vs CodeKata Score)"""

data["Previous Geekions"].mean()

data["CodeKata Score"].mean()

"""###### No of students participated """

len(data["Name"].unique())

""" #Average completion of python course or my_sql or python english or computational thinking"""

# combining two csv files without removing any columns

combine2=[pd1,pd2]
data2=pd.concat(combine2)
data2.head()

data2[['python',"mysql","python_en","computational_thinking"]].mean()

"""###### rising star of the week (top 3 candidate who performed well in that particular week)"""

data2.sort_values('Rising',ascending=False).head(3)

"""###### Shining stars of the week (top 3 candidates who has highest geekions)"""

data2.sort_values('CodeKata Score',ascending=False).head(3)

"""###### Department wise codekata performence (pie chart)"""

data2['Department'].unique()

df=data2[['Department','CodeKata Score']]
df.groupby(['Department']).sum().plot(kind='pie', y='CodeKata Score')

"""###### Department wise toppers (horizantal bar graph or any visual representations of your choice)"""

plott=data2.groupby('Department').head(1)
plott

plott.groupby(['Department']).sum().plot(kind='bar', y='CodeKata Score')